#+hugo_base_dir: ../../
#+hugo_section: posts
#+seq_todo: TODO DRAFT DONE
#+property: header-args :eval no

#+startup: indent
#+startup: content

# Macros
#+macro: doc [[https://ox-hugo.scripter.co/doc/$1][$2]]
#+macro: oxhugoissue =ox-hugo= Issue #[[https://github.com/kaushalmodi/ox-hugo/issues/$1][$1]]
#+macro: hugoissue =hugo= Issue #[[https://github.com/gohugoio/hugo/issues/$1][$1]]
#+macro: hugopr =hugo= PR #[[https://github.com/gohugoio/hugo/pull/$1][$1]]
#+macro: bfissue /Blackfriday/ Issue #[[https://github.com/russross/blackfriday/issues/$1][$1]]
#+macro: commit commit [[https://github.com/kaushalmodi/ox-hugo/commit/$1][$1]]
#+macro: latex @@html:<span class="latex">L<sup>a</sup>T<sub>e</sub>X</span>@@

#+AUTHOR: Louis Tsiattalou

* Technology                                                    :@Technology:
:PROPERTIES:
:END:
** DONE Replacing the T440p Trackpad                              :Thinkpad:
CLOSED: [2018-02-24 Sat 20:19] SCHEDULED: <2018-02-24 Sat>
:PROPERTIES:
:EXPORT_FILE_NAME: replacing-the-t440p-trackpad
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :featured thinkpad_stock.jpg :type post
:END:
This is difficult thing to do for a beginner, and there are virtually no step-by-step resources online that detail the optimal way to do this. Hopefully this blog post will address this!

*** But... Why?

The T440(p/s) and X240 series Thinkpads came with an /absolute trash/ trackpad; called the /clickpad/. I personally have no idea what Lenovo were thinking when they fit their new flagships with this thing. The entire thing was basically one large button, with no physical buttons at the top for TrackPoint users. It was loud, wobbly, and a downgrade in pretty much every way compared to the previously used T430 trackpads.

Luckily, Lenovo wised up and used standard trackpads and refitted the physical buttons when they released the xx50 series laptops. They had the exact same dimensions and ribbon connector as the T440's clickpad. Some clever cookie somewhere figured out you could retrofit the xx50 trackpads onto the xx40 Thinkpads. As somebody who just picked up a T440p on a bargain recently, I figured this is a must-have, as a TrackPoint user.

Unfortunately, there is a lot of misinformation online (talking about taking out the motherboard to replace the trackpad and other non-sensical rubbish). Anyone can follow this guide, it's quick and easy. This guide is for the T440p - there are resources online for the T440/T440s, but I don't imagine the process will be all that different for the T440p than those models. I haven't replaced an X-series clickpad, but again, I don't htink it'll be all that different.

You will need:
- A small Phillips screwdriver.
- A small flathead screwdriver/plastic wedge.
- A T450 trackpad.
- 20-40 minutes, depending on how experienced you are with taking apart laptops.

That's literally it.

*** Obtaining the Parts

*** Opening the Chassis

*** Removing the Keyboard & Ribbon Cables

*** Removing the HDD/Disk Drive

I'm not entirely sure this section is necessary, but I haven't tested it out /without/ doing this, I just did it anyway because the "guide" I was following told me to. Although halfway through following that I said "sod this" because I'm pretty sure it was full of crap and decided to go my own way.

*** Removing the Palm Rest

*** Replacing the Trackpad

*** Putting it all back together

* Data Science
